// DATA
export const books = [
  {
    id: 1,
          title: "Bleach",
          url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388508611l/2880.jpg",
          originalPrice: 15.95,
          salePrice: 14.95,
          rating: 4.5,
          summary: "Ichigo Kurosaki has always been able to see ghosts, but this ability doesn't change his life nearly as much as his close encounter with Rukia Kuchiki, a Soul Reaper and member of the mysterious Soul Society. While fighting a Hollow, an evil spirit that preys on humans who display psychic energy, Rukia attempts to lend Ichigo some of her powers so that he can save his family; but much to her surprise, Ichigo absorbs every last drop of her energy. Now a fully-fledged Soul Reaper himself, Ichigo quickly learns that the world he inhabits is one full of dangerous spirits, and along with Rukia, who is slowly regaining her powers, it's Ichigo's job to both protect the innocent from Hollows and to help the spirits themselves find peace.",
        },
        {
          id: 2,
          title: "One Piece",
          url: "https://covers.openlibrary.org/b/id/863527-L.jpg",
          originalPrice: 18.95,
          salePrice: 14.95,
          rating: 5,
          summary: "Luffy sets his sights on Sanji as their new cook but it will take more than a little sweet talk to get him to join Luffy's team. His vow to feed any and all pirates in need keeps getting in the way",
        },
        {
          id: 3,
          title: "Inuyasha",
          url: "https://covers.openlibrary.org/b/id/7802605-L.jpg",
          originalPrice: 13.95,
          salePrice: 10.95,
          rating: 4,
          summary: "Kagome Higurashi, a 15-year-old junior high school student, is dragged into the Bone Eater's Well by Mistress Centipede, an insect-demon. She escapes and emerges in the past. Kagome turns out to be the reincarnation from the deceased maiden Kikyo, with the sacred Shikon Jewel also reborn inside her body.",
        },
        {
          id: 4,
          title: "Vagabond",
          url: "https://covers.openlibrary.org/b/id/863362-L.jpg",
          originalPrice: 15.95,
          salePrice: 14.95,
          rating: 5,
          summary: "Miyamoto Musashi and Sasaki Kojiro's intertwining paths lead them toward what will be the greatest samurai duel in Japanese history. Sasaki Kojiro heads to Kokura for his new position as sword instructor for the powerful Hosokawa Clan. Meanwhile, Musashi is at a crossroads dealing with the aftermath of single-handedly destroying the mighty Yoshioka clan. After he starts to question his quest to be invincible and his whole reason for existence, will his confidence in himself ever be the same? For mature audiences.",
        },
        {
          id: 5,
          title: "Naruto",
          url: "https://covers.openlibrary.org/b/id/12729166-L.jpg",
          originalPrice: 5.55,
          salePrice: null,
          rating: 5,
          summary: "Naruto is a Japanese manga series written and illustrated by Masashi Kishimoto. It tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village.",
        },
        {
          id: 6,
          title: "Berserk",
          url: "https://covers.openlibrary.org/b/id/869292-L.jpg",
          originalPrice: 10.99,
          salePrice: null,
          rating: 4,
          summary: "Back in the day, Guts the Black Swordsman was a top slayer for The Band of the Hawk, an elite mercenary unit led by Griffith, whose calm demeanor and callow beauty belied his fighting prowess and steel will. While in a king's employ, the attraction between the king's daughter and Griffith and the growing favor of the king towards the Hawk leader raises the hackles of the king's jealous son, who plots to have Griffith summarily assassinated. But if the plot fails, the king's son will likely have to deal with Guts and his titanic broadsword, and the results of such confrontations are rarely pretty... or easy to clean up",
        },
        {
          id: 7,
          title: "Fruits Basket",
          url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1463562762l/28219400.jpg",
          originalPrice: 14.95,
          salePrice: 12.95,
          rating: 4.5,
          summary: "After a family tragedy turns her life upside down, plucky high schooler Tohru Honda takes matters into her own hands and moves out...into a tent! Unfortunately for her, she pitches her new home on private land belonging to the mysterious Sohma clan, and it isn't long before the owners discover her secret. But, as Tohru quickly finds out when the family offers to take her in, the Sohmas have a secret of their own--when touched by the opposite sex, they turn into the animals of the Chinese Zodiac!A perennial favorite of fans and librarians alike, Natsuki Takaya's beloved bestselling Fruits Basket series returns to print in gorgeous deluxe English-language omnibus editions with beautiful full-color illustrations that are not to be missed!",
        },
        {
          id: 8,
          title: "The Promised Neverland",
          url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1503365706l/34852836.jpg",
          originalPrice: 11.95,
          salePrice: 10.95,
          rating: 2.5,
          summary: "It’s the year 2045, 1000 years after humans and demons agreed to live peacefully in two “separate” worlds — on the condition that mankind obey one request. Central to this agreement is Grace Field House orphanage, where Emma, Norman, and Ray lead an idyllic life. The house’s walls have always protected them from the outside world, but when dark secrets start to seep through the cracks, the children are thrown on a terrifying adventure. Don’t let Demizu Posuka’s adorable artwork fool you: this masterful suspense story is horrifically chilling and utterly heartrending.",
        },
        {
          id: 9,
          title: "Tokyo Ghoul",
          url: "https://m.media-amazon.com/images/I/51gTbdvr9tL._SL500_.jpg",
          originalPrice: 14.95,
          salePrice: 13.95,
          rating: 4,
          summary: "It’s never fun to discover that somebody’s only into you for your body. But when Ken Kanuki realizes the beautiful Rize is only interested in eating his body, things turn sour pretty quickly. After a narrow escape and a lifesaving operation, Ken is forced to live as the first half-ghoul, half-human hybrid in a world where anthropoid ghouls sit at the top of the food chain. Ken’s struggle to exist in the space between two worlds is captured evocatively in this title’s sharp yet subtle art. But make no mistake, this action-packed manga is also dark, grotesque, and violent — definitely not for the faint of heart.",
        },
        {
          id: 10,
          title: "The Gentleman's Alliance",
          url: "https://covers.openlibrary.org/b/id/9011745-L.jpg",
          originalPrice: 14.95,
          salePrice: null,
          rating: 3.5,
          summary: "Haine joins the student council at an elite academy to get to know the boy who rescued her long ago. Haine has been in love with Shizumasa Togu since she read the fairy tale he wrote as a child. However, the Emperor is so well sequestered by the student council that she hasn't been able to speak to him in the three months she's been at the academy. And as rumor has it, he already has a lover...",
        },
        {
          id: 11,
          title: "Dororo",
          url: "https://m.media-amazon.com/images/I/512MiXrl9EL._SL500_.jpg",
          originalPrice: 12.95,
          salePrice: null,
          rating: 5,
          summary: "Tezuka's classic thriller manga featuring a youth who has been robbed of 48 body parts by devils and his epic struggle against a host of demons to get them back. Daigo Kagemitsu, who works for a samurai general in Japan's Warring States period, promises to offer body parts of his unborn baby to 48 devils in exchange for complete domination of the country. Knowing the child to be deficient, Kagemitsu oderes the newborn to be thrown into the river. The baby survives and, in time, searches the world for the 48 demons. Each time he eliminates one, he retrieves one of his parts.",
        },

        {
          id: 12,
          title: "Vinland Saga",
          url: "https://m.media-amazon.com/images/I/51stD1wi6AL._SL500_.jpg",
          originalPrice: 16.95,
          salePrice: 14.95,
          rating: 5,
          summary: "Soon to be a major anime series from the makers of Attack on Titan! FOR HONOR AND VENGEANCE As a child, Thorfinn sat at the feet of the great Leif Ericson and thrilled to wild tales of a land far to the west. But his youthful fantasies were shattered by a mercenary raid. Raised by the Vikings who murdered his family, Thorfinn became a terrifying warrior, forever seeking to kill the band's leader, Askeladd, and avenge his father. Sustaining Throfinn through his ordeal are his pride in his family and his dreams of a fertile westward land, a land without war or slavery...the land Leif called Vinland.",
        },
];